import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import { CommonSection } from '@/components/layouts/CommonSection';
import { Header } from '@/components/layouts/Header';
import { Footer } from '@/components/layouts/Footer';
import { BreadcrumbProvider } from '@/providers/BreadcrumbProvider';
import { Breadcrumb } from '@/components/ui/Breadcrumb';
import { BodyLayout } from '@/components/layouts/BodyLayout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ドキュメント',
  description: 'Generated by ドキュメント',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth scroll-pt-(--HEADER_HEIGHT)`}
      data-scroll-behavior="smooth"
    >
      <BodyLayout>
        <Header />
        <BreadcrumbProvider>
          <Breadcrumb />
          <main className="reset-margin">
            <CommonSection>{children}</CommonSection>
          </main>
        </BreadcrumbProvider>
        <Footer />
      </BodyLayout>
    </html>
  );
}
